#!/bin/bash

git clone https://github.com/sergiocazzolato/validator.git

sudo apt update
sudo apt install -y awscli snapcraft python3-pip
sudo pip3 install psutil
sudo snap install ubuntu-image --classic

# sudo su
# snapcraft login
# gcloud auth application-default login
# gcloud auth login
# exit

sudo mkdir -p /root/.config
sudo cp -rf /home/ubuntu/.config/snapcraft /root/.config
