#!/bin/bash

git clone https://github.com/sergiocazzolato/validator.git

sudo apt update
sudo apt install -y ubuntu-image awscli snapcraft python3-pip
sudo pip3 install psutil

# sudo aws configure
sudo cp -rf /home/ubuntu/.aws /root/.aws
# sudo snapcraft login
sudo mkdir -p /root/.config
sudo cp -rf /home/ubuntu/.config/snapcraft /root/.config
